add tests for copp manager redesign
JibinBao/sonic-mgmt pull request #12
Opened 2021-12-29 02:01 UTC by JibinBao

### Description of PR

Add tests  for CoPP Manager redesign feature
1. CoPP Manger redesign test plan: https://github.com/Azure/SONiC/pull/903
2. HLD: https://github.com/noaOrMlnx/sonic-swss/blob/4865a8eb37444c2c070ef49cc69690e4295ce07d/doc/copp_redisgn.md

Summary:
Fixes # (issue)

### Type of change

- [ ] Bug fix
- [ ] Testbed and Framework(new/improvement)
- [x] Test case(new/improvement)

### Back port request
- [ ] 201911

### Approach
#### What is the motivation for this PR?
Add new tests for CoPP Redesign feature.

#### How did you do it?
Add new tests

#### How did you verify/test it?
Run New CoPP tests

#### Any platform specific information?

#### Supported testbed topology if it's a new test case?

### Documentation

2021-12-29 07:38 UTC, nhe-NV reviewed
It should be bool

2021-12-31 03:50 UTC, nhe-NV commented on tests/copp/copp_utils.py
> +    configure_always_enabled_for_trap(dut, trap, "true")
the value should be bool as described in the function define

2021-12-31 03:50 UTC, nhe-NV commented on tests/copp/copp_utils.py
> +        trap (str): trap name
this should be trap name or trap id? in the configure_always_enabled_for_trap it is described as trap id

2021-12-31 03:50 UTC, nhe-NV commented on tests/copp/copp_utils.py
> +    Configure the always_enabled to True or False for the specified trap Id.
trap_id： the explain if trap id should be consistent

2021-12-31 03:50 UTC, nhe-NV commented on tests/copp/copp_utils.py
> +    config_db_json = dut.shell("/usr/local/bin/sonic-cfggen -d --print-data")["stdout"]
sudo sonic-cfggen

2021-12-31 03:50 UTC, nhe-NV commented on tests/copp/copp_utils.py
> +        always_enabled (Bool): True or False
should be string, not bool

2021-12-31 03:50 UTC, nhe-NV commented on tests/copp/copp_utils.py
> +        trap (str): trap name
is it trap id?

2021-12-31 03:50 UTC, nhe-NV commented on tests/copp/copp_utils.py
> +        trap (str): trap name
trap id or trap name?

2021-12-31 03:50 UTC, nhe-NV commented on tests/copp/copp_utils.py
> +        always_enable_value (bool): True or False
string or bool?

2021-12-31 03:50 UTC, nhe-NV commented on tests/copp/test_copp.py
> +    trap_name = "bgp"
need to make it consistent for trap name , trap id

2021-12-31 03:50 UTC, nhe-NV commented on tests/copp/test_copp.py
> +        Validates that one new tarp(bgp) can be installed
typo

2021-12-31 03:50 UTC, nhe-NV commented on tests/copp/test_copp.py
> +        Validates that The tarp(bgp) can be uninstalled after deleting the corresponding entry from the feature table
typo

2021-12-31 03:50 UTC, nhe-NV commented on tests/copp/test_copp.py
> +        Validates that The tarp(bgp) can be uninstalled after deleting the corresponding entry from the feature table
the not The

2021-12-31 03:50 UTC, nhe-NV commented on tests/copp/test_copp.py
> +        2. Remove bgp entry from feature table with CMD follow:
True to true

2021-12-31 03:50 UTC, nhe-NV commented on tests/copp/test_copp.py
> +        logger.info("Set always_enabled of {} to False".format(self.trap_name))
false

2021-12-31 03:50 UTC, nhe-NV commented on tests/copp/test_copp.py
> +        Validates that The tarp(bgp) can be uninstalled after disabling the corresponding entry from the feature table
typo

2021-12-31 03:50 UTC, nhe-NV commented on tests/copp/test_copp.py
> +        Validates that The tarp configuration is saved or not after reboot(reboot, fast-reboot, warm-reboot)
the not The

2021-12-31 03:50 UTC, nhe-NV commented on tests/copp/test_copp.py
> +        1. Set always_enabled of a trap(e.g. bgp) to True
true not True

2021-12-31 07:36 UTC, nhe-NV commented on tests/copp/copp_utils.py
> +    dut.command("sudo cp {} {}".format(_TEMP_CONFIG_DB, _CONFIG_DB))
should delete the tmp_config_db?

2021-12-31 07:56 UTC, nhe-NV approved these changes

2022-01-03 15:43 UTC, noaOrMlnx requested changes

2022-01-03 15:43 UTC, noaOrMlnx commented on tests/copp/test_copp.py
> +    """Skips this test if the SONiC image installed on DUT is older than 202106
copp new logic should be in 202012 branch and above

2022-01-03 15:43 UTC, noaOrMlnx commented on tests/copp/test_copp.py
> +    skip_release(duthosts[enum_rand_one_per_hwsku_frontend_hostname], ["201911"])
what about older releases? 

Also, please add new line at EOF

2022-01-03 15:43 UTC, noaOrMlnx commented on tests/copp/test_copp.py
> +        1. Set always_enabled of bgp to true to make sure trap(bgp) is installed
why would you set always_enable to true and then delete the feature entry? 
if always_enabled is true, and feature entry is removed, the trap should be installed.

2022-01-03 15:43 UTC, noaOrMlnx commented on tests/copp/copp_utils.py
> +    Uninstall trap by disabling feature and set always_enable to false
please fix the comment and args

2022-01-03 15:43 UTC, noaOrMlnx commented on tests/copp/copp_utils.py
> +    dut.command('redis-cli -n 4 hdel "FEATURE|{}" "auto_restart" "has_global_scope" "has_per_asic_scope" "has_timer" '
can be changed to "redis-cli -n 4 del FEATURE|name"
it will delete the whole entry

2022-01-04 05:36 UTC, JibinBao commented on tests/copp/copp_utils.py
> +    Uninstall trap by disabling feature and set always_enable to false
fix

2022-01-04 05:49 UTC, JibinBao commented on tests/copp/test_copp.py
> +        1. Set always_enabled of bgp to true to make sure trap(bgp) is installed
Actually I set the always_enable to false later.
I think you suggestion is better, I will install the trap by enabling feature status

2022-01-04 06:07 UTC, JibinBao commented on tests/copp/copp_utils.py
> +    dut.command('redis-cli -n 4 hdel "FEATURE|{}" "auto_restart" "has_global_scope" "has_per_asic_scope" "has_timer" '
fix

2022-01-04 06:07 UTC, JibinBao commented on tests/copp/test_copp.py
> +    """Skips this test if the SONiC image installed on DUT is older than 202106
ok

2022-01-04 06:11 UTC, JibinBao commented on tests/copp/test_copp.py
> +    skip_release(duthosts[enum_rand_one_per_hwsku_frontend_hostname], ["201911"])
For 201811 we don't support it anymore

2022-01-04 11:30 UTC, noaOrMlnx approved these changes

2022-01-05 01:59 UTC, JibinBao commented
close it, and open external one

2022-01-05 01:59 UTC, closed without merging